In [16]:
from numpy import random
import numpy as np
import matplotlib.pyplot as plt

0.05533402290765199

In [105]:

sample_size_list = [5, 10, 50, 100, 1000, 10000]
repetition = 1

annualized_list = np.array([])
average_list = np.array([])

for N in sample_size_list:
    annualized = 0
    average = 0
    
    for _ in range(repetition):
        vals = random.uniform(-0.5, 1, N)
        annualized += np.prod(vals+1)**(1/len(vals))-1
        average += np.mean(vals)

        
    annualized_list = np.append(annualized_list, annualized/repetition)
    average_list = np.append(average_list, average/repetition)
    
print("Annualized", annualized_list)
print("AVG", average_list)
print((annualized_list-average_list)/average_list)

Annualized [ 0.0047775  -0.17755982  0.15696439  0.13363014  0.18019099         inf]
AVG [ 0.04838013 -0.13147792  0.24358632  0.2223037   0.26392824  0.25126172]
[-0.90125081  0.3504916  -0.35561081 -0.39888477 -0.31727279         inf]


In [133]:
def annualized_average_return_under_uniform(low, high, N=1000, rep=5000):
    annualized = 0
    average = 0
    for _ in range(rep):
        vals = random.uniform(low, high, N)
        annualized += np.prod(vals+1)**(1/len(vals))-1
        average += np.mean(vals)
    return(annualized/rep, average/rep)

annualized_average_return_under_uniform(-0.5, 1)

(0.1679010127433061, 0.24989503213384906)

In [189]:
capital = 10000
days = [5, 10, 100, 365, 720, 1500]
annualized_errors = np.array([])
average_errors = np.array([])
low = -0.1
high = 0.2
annual, avg = annualized_average_return_under_uniform(low, high)
annual = annual+1
avg = avg+1

for d in days:
    m = capital
    for _ in range(d):
        val = random.uniform(low, high, 1)[0]
        m = m * (1 + val)

    annualized_errors = np.append(annualized_errors, abs(m-capital*(annual**d)))
    average_errors = np.append(average_errors, abs(m-capital*(avg**d)))
    
print(annualized_errors)
print(average_errors)

[3.72119361e+02 1.64811804e+03 6.68261455e+05 4.71316901e+11
 2.08187097e+18 2.32791653e+31]
[1.55718097e+02 2.19573464e+03 2.88380485e+05 8.87250256e+10
 1.40898871e+19 5.79265283e+35]


In [180]:
capital = 10000
days = [5, 10, 100, 365]
annualized_errors = np.array([])
average_errors = np.array([])
low = -0.5
high = 1
annual, avg = annualized_average_return_under_uniform(low, high)
annual = annual+1
avg = avg+1

for d in days:
    m = capital
    val = random.uniform(low, high, 1)[0]
    for _ in range(d):
        m = m * (1 + val)

    annualized_errors = np.append(annualized_errors, abs(m-capital*(annual**d)))
    average_errors = np.append(average_errors, abs(m-capital*(avg**d)))
    
print(annualized_errors)
print(average_errors)

[2.08311924e+04 8.18957986e+03 6.91030276e+30 4.12192905e+28]
[2.96030181e+04 3.76389818e+04 6.91030276e+30 2.30529008e+39]


In [116]:
capital = 10000
days = [5, 10, 100, 365, 720]
annualized_errors = np.array([])
average_errors = np.array([])

for d in days:
    reserve = 0
    for _ in range(d):
        val = random.uniform(-0.5, 1, 1)
        reserve +=  capital*(1+val)-capital
    
    print(reserve)
    average_errors = np.append(average_errors, abs(reserve-(capital+capital*0.25*10))/reserve)
    
print(average_errors)

[1500.58894414]
[57204.48503034]
[280840.04578288]
[1006739.46489243]
[1741341.62006255]
[22.32417558  0.38815986  0.8753739   0.9652343   0.97990056]
